### ISSUE TITLE
[Update] Update README with New Features and Instructions

### ISSUE THREAD

**Issue by Satyam1923** [Satyam1923/Spring-Music-Player#14] opened 2024-05-06 13:12 UTC
As soon as the issue get fix. It's crucial to update the README file to provide comprehensive guidance for new contributors and developers interested in learning about and contributing to the project.

**Comment by sadvika05** [comment] 2024-05-09 05:50
Hi @Satyam1923,

Once the issue is resolved, updating the README file will be essential to ensure that new contributors and developers have comprehensive guidance on understanding and contributing to the project.

I'd like to take on the responsibility of updating the README to reflect the changes and provide clear instructions for anyone interested in joining our project. Could you please assign this task to me?

Looking forward to contributing further!

**Comment by Satyam1923** [comment] 2024-05-09 06:13
@Satyam1923 Go on!

**Comment by amishah1110** [comment] 2024-05-10 06:01
To guarantee clarity for new contributors, I think it's essential to update the README after fixing the issue. I'm excited to assume this role and offer thorough direction.

Would you kindly give me the assignment of revising the README?

**Comment by Satyam1923** [comment] 2024-05-10 07:37
@amishah1110 @sadvika05 @anushkapal28 you can update the readme file for better clarification.

**Comment by Techkunjan** [comment] 2024-05-12 13:56
I would like to help in the revising of the readme file for better understanding . @Satyam1923 Would you kindly assign this task?

**Comment by T-ShubhAM2002** [comment] 2024-05-17 06:28
I would like to help in  revising of the readme file for better understanding . @Satyam1923 Would you kindly give me the assignment of revising the README?

**Closed** 2024-05-18 09:20 UTC
Labels: documentation, enhancement, help wanted, good first issue, gssoc, level1
